package middleware

import (
	"net/http"

	"github.com/go-chi/chi/v5"

	"github.com/Justdan111/credflow-api/pkg/response"
)

// ValidateUUIDParams rejects malformed path parameters before a handler runs.
//
// Without it a request for /api/customers/not-a-uuid reaches Postgres, which
// refuses the cast, and the repository's error surfaces as a 500 — a client
// mistake reported as a server fault. That is misleading to whoever is
// debugging it and it puts junk in the error logs that looks like an outage.
//
// Mount it on a nested Route that owns the id segment — r.Route("/{customerId}",
// ...) — not on the parent group. chi only fills URL parameters once the pattern
// carrying them has been matched, so middleware added to the parent sees an
// empty value and silently validates nothing. Nesting also makes the guarantee
// structural: every route under that subtree inherits the check and cannot
// forget it, the same property BodyLimit gets from being global.
func ValidateUUIDParams(names ...string) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			for _, name := range names {
				value := chi.URLParam(r, name)
				// Absent means this route does not carry that parameter, which
				// is normal when one group mounts several shapes of path.
				if value == "" || IsUUID(value) {
					continue
				}
				response.Fail(w, http.StatusBadRequest, name+" must be a UUID")
				return
			}
			next.ServeHTTP(w, r)
		})
	}
}

// IsUUID reports whether s is a canonical 36-character UUID.
//
// Hand-rolled rather than pulling in a UUID dependency for one predicate. The
// check is deliberately strict: Postgres also accepts braced and unhyphenated
// forms, but allowing several spellings of the same id means the same resource
// has several URLs, which breaks caching and makes logs harder to correlate.
//
// The version and variant nibbles are not checked. Ids are generated by the
// database, so this only needs to stop a malformed value reaching the driver,
// not to certify how a well-formed one was produced.
func IsUUID(s string) bool {
	const uuidLength = 36
	if len(s) != uuidLength {
		return false
	}
	for i := 0; i < uuidLength; i++ {
		c := s[i]
		if i == 8 || i == 13 || i == 18 || i == 23 {
			if c != '-' {
				return false
			}
			continue
		}
		isDigit := c >= '0' && c <= '9'
		isLower := c >= 'a' && c <= 'f'
		isUpper := c >= 'A' && c <= 'F'
		if !isDigit && !isLower && !isUpper {
			return false
		}
	}
	return true
}
